.\" Copyright (c) 2022, Rafael Santiago
.\" All rights reserved.
.\"
.\" This source code is licensed under the BSD-style license found in the
.\" LICENSE file in the root directory of this source tree.
.TH BOOJUM_DEINIT 3 "June 16, 2022" "version 0x20220001" "BOOJUM's API"
.SH NAME
boojum_deinit \- deinitializes \fIBoojum\fR memory protection system

.SH SYNOPSIS
.nf
.B #include <boojum.h>

.BI
.BI "int boojum_deinit(void);
.fi

.SH DESCRIPTION
The
.BR boojum_deinit ()
function deinitializes the memory protection system previous
well-initialized with
.BR boojum_init ().

.PP
.SH RETURN VALUE
On success,
.BR boojum_deinit ()
returns \fIEXIT_SUCCESS\fR, on failure it returns \fIEXIT_FAILURE\fR
or the exact error value defined in \fI<errno.h>\fR.

.PP
.SH
SEE ALSO
.BR boojum_init (3)

.SH COLOPHON
This page is part of \fIlibboojum\fR. You can find more information at
\%https://github.com/rafael-santiago/boojum. There you can also find
newest releases, areas for reporting issues besides more technical
discussions.
